# Guideline
## 1. No 500 status code
## 2. Skip unnecessary description
## 3. Lower case except long description

openapi: 3.1.0
info:
  title: Common App
  description: The API for Common APP
  version: 0.0.0

servers:
  - url: 'http://localhost:8080'
    description: development environment
  - url: 'https://patjiang.dpdns.org'
    description: production environment

security:
  - BearerAuth: []

tags:
  - name: Auth
    description: authentication group

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OneTimeBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # Business Objects
    AuthResponse:
      type: object
      required:
        - access_token
        - token_type
        - expires_in
        - refresh_token
        - user_id
      properties:
        access_token:
          type: string
          description: JWT
        token_type:
          type: string
        expires_in:
          type: integer
        refresh_token:
          type: string
        user_id:
          type: integer
          format: int64
          description: unsigned integer 54
    # Basics
    Username:
      type: string
      maxLength: 50
      description: only letters and digits
    Password:
      type: string
      minLength: 8
      maxLength: 20
      pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).*$'
      description: >
        must be 8-20 characters long, and contain at least one lowercase letter, 
        one uppercase letter, one digit, and one special character
    Email:
      type: string
      format: email
      maxLength: 255
    Scene:
      type: string
      enum: [signup, reset_password]
    Error:
      type: object
      required: [error]
      properties:
        code:
          type: string
          example: ATK_EXPIRED
        error:
          type: string

paths:
  /auth/create-account:
    post:
      summary: create account using email from jwt, password
      tags: [Auth]
      security: [{ OneTimeBearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [password]
              properties:
                password:
                  $ref: '#/components/schemas/Password'
      responses:
        '200':
          description: account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: bad request
        '401':
          description: unauthorized, invalid scene/expired token/invalid token
        '409':
          description: email already exists

  /auth/verify-code:
    post:
      summary: check the code sent via email
      tags: [Auth]
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, scene, code, code_id]
              properties:
                email:
                  $ref: '#/components/schemas/Email'
                scene:
                  $ref: '#/components/schemas/Scene'
                code:
                  type: string
                code_id:
                  type: string
      responses:
        '200':
          description: verify code successfully
          content:
            application/json:
              schema:
                type: object
                required: [token]
                properties:
                  token:
                    type: string
        '400':
          description: invalid request body
        '401':
          description: invalid code or expired
        '429':
          description: too many request

  /auth/request-code:
    post:
      summary: apply for verification code
      tags: [Auth]
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, scene]
              properties:
                email:
                  $ref: '#/components/schemas/Email'
                scene:
                  $ref: '#/components/schemas/Scene'
      responses:
        '200':
          description: always return true to avoid attacks
          content:
            application/json:
              schema:
                type: object
                required: [code_id]
                properties:
                  otp_id:
                    type: string
        '400':
          description: invalid request
        '429':
          description: frequency limit


  /ping:
    get:
      summary: check server health
      security: []
      responses:
        '200':
          description: server is working correctly
          content:
            text/plain:
              example: 'pong'